apiVersion: v1
kind: Secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFTSUEySjRGSEQ3M1BNSENBUk1PCmF3c19zZWNyZXRfYWNjZXNzX2tleT1rSzlzL011SHpWV2pPOXQxdlFGMThyZlNpRU5QM3JTYXc3Ync4Z3ZaCmF3c19zZXNzaW9uX3Rva2VuPUZ3b0daWEl2WVhkekVFSWFETE9hMHM0Kyt3WXRlc005V2lMVkFYNklaWW9XRlptaDU3NUhLaFlYcXdJS29DVnh5Wi9yZ1BybnVWM0NpM3MrY0xBaHFBN0tkSlA5WUlDYzgvaWxLOVpPci9FSmtuRmFRSm8vNmxkWFc3eHQrS29jOEFXM2lqcW5DaiszSmNwcVo1eFVkVUN0eWFlM1ZveWFRelpxN2VxUWo0Z2lOb0RpTlNKdFVQZXdCVmdoVXFybUZZMnJPNHdabmwrM09VWGo0ME5Zb1g0Wm9FbERPdW5QalRIbzhmcHNrSy9nbmgwMFNuRXJwS0dYUnd4N0FXNDczS3M2NThBWUZqQ2JvejBrN3JhSUhJMFkzQzEvUi9xay9NNk9rbzNFQ1FpYnI5M3N5cFVVdXlORkdyeTZOMlp4akNqYjJ0T3FCakl0Ylk0alF5MkhVcFo1YXY5andJb3BBZjZjeFVEMDlsL1grUFBDSVAvVHZTWGc5bW56RlFEWEdLZlZUN2FU
metadata:
  name: aws-secret