apiVersion: v1
kind: Secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFTSUEySjRGSEQ3M0REUldCT09aCmF3c19zZWNyZXRfYWNjZXNzX2tleT1VOEhMVW9pT01pVDdBYmoyZWkyM1JFTkxLWjM1cS9kdWNBelhQSVBkCmF3c19zZXNzaW9uX3Rva2VuPUZ3b0daWEl2WVhkekVEOGFESWw2UVZHby9hbFJ1ZHBlM3lMVkFlVS9kMm5GcVhRZWRycThRQjhPUGxBUnlVSTN1M0xZY2RJM1ZoRi9VVW44RzRvU1hVT1Uya0t3S3cwRkVSMy9SamJzdHNnZ0p2U1NpM0ZlREZnWVJrdWxiY0cwelJHcFdBWkludzh2Z0VmUEVmOVZSdTcwL2Z2bFoxZEhLK3V3YXcyZ0tlRlp5bjdHTkU1RVRTWDhYb3dxODVGZmRiSWh2VldLTG5JWTZOR0hkdzFoVDU5c3I2MWIyOHNSdER4OUp3YmhGb1RZWlBudmwwVzRDS1ZBNTMvRk1UK3FTbTR1TTRiemtaSTh4OUwzejhNNG9UNzBjR2FvUlRjdlpHaWVIQ0Mzb3oxUFdXbk5aOE15RDlkQlpUT2tveVY2emlpU2pOT3FCakl0azlRTVFmTWRuZldrK3FTdkVzSW84NFpvKzhFeVRjWS9adWZpN2ZLWHdPQXlQWm5lMVU5VGlYNjIyMWptCg==
metadata:
  name: aws-secret